### ISSUE TITLE
Issue when running with python3

### ISSUE THREAD

**Issue by XoxXix** [Ycmelon/webtoondl#20]
Traceback (most recent call last):
  File "webtoondl.py", line 23, in <module>
    @lru_cache
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

**Screenshots**
![Capture](https://user-images.githubusercontent.com/55496235/74277371-6c16d180-4d3d-11ea-8408-548a1700d14b.PNG)

**Solved**
By just changing @lru_cache to @lru_cache()

**Comment by XoxXix** [comment]
https://bugs.python.org/issue32001
![image](https://user-images.githubusercontent.com/55496235/74277857-4211df00-4d3e-11ea-8ae4-c254bbb7dc04.png)

**Comment by Ycmelon** [comment]
Thanks for your report!
What version of python are you using?

**Comment by XoxXix** [comment]
Python 3.6.9

**Comment by Ycmelon** [comment]
Sorry for the late response. The code works fine for newer versions of Python (I'm using 3.8), so I'd rather not change it and break newer versions 😬 Thank you for the report though! I'll keep that in mind.
